apiVersion: cache.razkevich.dev/v1alpha1
kind: ValkeyCluster
metadata:
  name: try
  namespace: default
spec:
  shards: 3
  replicasPerShard: 2
  image: valkey/valkey:8
  storage:
    size: 1Gi
  resources:
    requests: { cpu: 200m, memory: 256Mi }
    limits: { cpu: "1", memory: 512Mi }
  persistence:
    mode: AOFAndRDB
    appendFsync: everysec
  performance:
    ioThreads: 2
    maxmemoryPolicy: noeviction
  haPolicy:
    minReplicasToWrite: 1
    requireFullCoverage: true
    clusterNodeTimeoutMillis: 5000
