apiVersion: cache.razkevich.dev/v1alpha1
kind: ValkeyCluster
metadata:
  labels:
    app.kubernetes.io/name: valkeycluster
    app.kubernetes.io/managed-by: kustomize
  name: valkeycluster-sample
spec:
  replicas: 3
  image: valkey/valkey:8
